// Define page identifiers, routes and display metadata in one place.
// Synthetic interface fixtures. No real users, model predictions or health checks.
export const pages = [
  ["C03", "Candidate", "Upload CV", "/candidate/resumes", "Upload CV", "Import a temporary PDF and extract professional facts."],
  ["C04", "Candidate", "Review facts", "/candidate/resumes/example", "Review Facts", "Confirm professional JSON before cloud publication."],
  [
    "R01",
    "Research",
    "Experiments",
    "/research/experiments",
    "Research Experiments",
    "Design controlled studies with frozen jobs, protocols and model versions.",
  ],
  [
    "R02",
    "Research",
    "Create experiment",
    "/research/experiments/new",
    "Create Experiment",
    "Define seven required settings before selecting subjects.",
  ],
  [
    "R03",
    "Research",
    "Experiment details",
    "/research/experiments/EXP-001",
    "Experiment Details",
    "Inspect frozen configuration and within-method comparisons.",
  ],
  [
    "R04",
    "Research",
    "Subjects",
    "/research/cases",
    "Research Subjects",
    "Select eligible professional profiles with valid research grants.",
  ],
  [
    "R05",
    "Research",
    "Models",
    "/research/models",
    "Research Models",
    "Inspect versioned Neutral ML and Biased ML model packages.",
  ],
  [
    "R06",
    "Research",
    "Metrics",
    "/research/metrics?experimentId=EXP-001",
    "Experiment Metrics",
    "Evaluate each method using explicit sample denominators.",
  ],
  [
    "V01",
    "Review",
    "My tasks",
    "/reviewer/tasks",
    "My Review Tasks",
    "Review responsibilities assigned to your account.",
  ],
  [
    "V02",
    "Review",
    "Task details",
    "/reviewer/tasks/REV-001",
    "Review Task Details",
    "Assess professional evidence independently under blind-review constraints.",
  ],
  [
    "A01",
    "Administration",
    "Users",
    "/admin/users",
    "User Management",
    "Account status and authorized role assignments.",
  ],
  [
    "A02",
    "Administration",
    "Roles & permissions",
    "/admin/roles",
    "Roles & Permissions",
    "Module permissions are separate from case-level grants.",
  ],
  [
    "A03",
    "Administration",
    "Model releases",
    "/admin/models",
    "Model Versions & Release",
    "Manage tested, approved, active and retired versions.",
  ],
  [
    "A04",
    "Administration",
    "Frozen protocols",
    "/admin/protocols",
    "Frozen Protocols",
    "Read immutable assessment and feature definitions.",
  ],
  [
    "A05",
    "Administration",
    "Service health",
    "/admin/system-health",
    "Service Health",
    "Inspect service availability and temporary-file cleanup.",
  ],
  [
    "A06",
    "Administration",
    "Failures",
    "/admin/failures",
    "Failed Jobs & Errors",
    "Inspect sanitized failures and queue permitted retries.",
  ],
  [
    "A07",
    "Administration",
    "Audit logs",
    "/admin/audit",
    "Audit Logs",
    "Read authorized, non-content operation metadata.",
  ],
];
