"""Validate versioned selection and human-reviewed equivalence tables."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from .models import PreparationError


def review_identity(payload: dict[str, Any]) -> None:
    """Require an identified reviewer and a timezone-aware review time."""
    if not isinstance(payload.get("reviewer"), str) or not payload["reviewer"].strip():
        raise PreparationError("A completed review needs a reviewer identifier.")
    try:
        timestamp = datetime.fromisoformat(payload["reviewed_at"].replace("Z", "+00:00"))
    except (KeyError, TypeError, ValueError, AttributeError) as error:
        raise PreparationError("A completed review needs an ISO review time.") from error
    if timestamp.tzinfo is None or timestamp.utcoffset() is None:
        raise PreparationError("Review timestamps must include a timezone.")


def load_selection(path: Path) -> dict[str, Any]:
    """Read explicit source category filters, which do not approve facts.

    Shape: ``{version, sources: {source_id: {category_field, categories}}}``.
    ``categories`` maps exact publisher labels to provisional IT families.
    The source category is retained; selection is never inferred from a
    title, school, name, photograph, or demographic attribute.
    """
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not payload.get("version") or not isinstance(payload.get("sources"), dict):
        raise PreparationError("Selection needs a version and explicit source filters.")
    for selection in payload["sources"].values():
        if not isinstance(selection, dict) or not selection.get("category_field"):
            raise PreparationError("Each selection needs a source category field.")
        categories = selection.get("categories")
        if not isinstance(categories, dict) or not categories:
            raise PreparationError("Each selection needs explicit IT category mappings.")
        if any(not isinstance(key, str) or not isinstance(value, str) or not value.strip()
               for key, value in categories.items()):
            raise PreparationError("Selection categories and families must be nonempty text.")
    return payload


def load_reviewed_mappings(path: Path) -> dict[str, Any]:
    """Load approved codes and equivalences without supplying defaults.

    Alias/degree/language tables are exact source wording to code maps.
    Degree and language order are explicit, reviewed lists. No CEFR or
    degree equivalence is generated by this loader. ``version`` must
    change when a reviewed table changes.
    """
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    if not payload.get("version") or payload.get("status") != "APPROVED":
        raise PreparationError("Professional corrections require approved versioned mappings.")
    review_identity(payload)
    for key in ("skill_aliases", "degree_levels", "language_levels"):
        table = payload.get(key)
        if not isinstance(table, dict) or any(
            not isinstance(raw, str) or not raw or not isinstance(code, str) or not code
            for raw, code in table.items()
        ):
            raise PreparationError("Reviewed equivalence tables must map wording to codes.")
    for key in (
        "degree_order", "language_level_order", "language_codes", "subject_codes",
        "job_family_codes", "project_condition_codes",
    ):
        codes = payload.get(key)
        if not isinstance(codes, list) or any(
            not isinstance(code, str) or not code for code in codes
        ):
            raise PreparationError("Reviewed code inventories must be explicit string lists.")
        if len(set(codes)) != len(codes):
            raise PreparationError("Reviewed code inventories cannot repeat codes.")
    if not set(payload["degree_levels"].values()).issubset(payload["degree_order"]):
        raise PreparationError("Degree equivalents must occur in the reviewed ordering.")
    if not set(payload["language_levels"].values()).issubset(payload["language_level_order"]):
        raise PreparationError("Language equivalents must occur in the reviewed ordering.")
    return payload
