// Provide synthetic records for UI development without accessing production data.
// Synthetic frontend records; never a production database adapter.
export const fixtures = {
  experiments: [
    {
      id: "EXP-001",
      name: "Gender attribute study",
      type: "Single-factor paired",
      job: "Software Engineer v3",
      subjects: 24,
      status: "Completed",
      protocol: "P-2026.01",
      date: "2026-10-08",
    },
    {
      id: "EXP-002",
      name: "Age attribute analysis",
      type: "Single-factor paired",
      job: "Data Analyst v2",
      subjects: 0,
      status: "Draft",
      protocol: "P-2026.01",
      date: "2026-10-07",
    },
    {
      id: "EXP-003",
      name: "Controlled language comparison",
      type: "Single-factor paired",
      job: "Backend Developer v1",
      subjects: 32,
      status: "Queued",
      protocol: "P-2026.01",
      date: "2026-10-06",
    },
    {
      id: "EXP-004",
      name: "Baseline validation",
      type: "Baseline",
      job: "Software Engineer v3",
      subjects: 16,
      status: "Completed",
      protocol: "P-2026.01",
      date: "2026-10-05",
    },
  ],
  subjects: [
    {
      id: "SUB-001",
      source: "Reviewed Profiles",
      name: "Software Engineer",
      status: "Eligible",
      skills: "Java, SQL, Git",
      education: "Bachelor / Computer Science",
    },
    {
      id: "SUB-002",
      source: "Reviewed Profiles",
      name: "Backend Developer",
      status: "Eligible",
      skills: "Java, Docker",
      education: "Master / Software Engineering",
    },
    {
      id: "SUB-003",
      source: "Authorized Candidate Cases",
      name: "Data Analyst",
      status: "Eligible",
      skills: "SQL, Python",
      education: "Bachelor / Mathematics",
    },
    {
      id: "SUB-004",
      source: "Authorized Candidate Cases",
      name: "Restricted case",
      status: "Grant revoked",
      skills: "Unavailable",
    },
    {
      id: "SUB-005",
      source: "Reviewed Profiles",
      name: "Expired profile",
      status: "Expired",
      skills: "Unavailable",
    },
  ],
  models: [
    {
      id: "N-2026.01",
      name: "Neutral ML",
      version: "1.0.0",
      status: "Active",
      schema: "32 inputs",
      protocol: "P-2026.01",
      mode: "Professional block + zero research block",
    },
    {
      id: "B-2026.01",
      name: "Biased ML",
      version: "1.0.0",
      status: "Active",
      schema: "32 inputs",
      protocol: "P-2026.01",
      mode: "Professional block + declared research attributes",
    },
    {
      id: "N-2026.02",
      name: "Neutral ML",
      version: "1.1.0",
      status: "Tested",
      schema: "32 inputs",
      protocol: "P-2026.01",
      mode: "Professional block + zero research block",
    },
  ],
  tasks: [
    {
      id: "REV-001",
      name: "Software Engineer v3",
      case: "CASE-101",
      mode: "Standard",
      status: "Pending",
      date: "2026-10-08",
    },
    {
      id: "REV-002",
      name: "Backend Developer v1",
      case: "CASE-102",
      mode: "Instructed-Bias",
      status: "Pending",
      date: "2026-10-08",
    },
    {
      id: "REV-003",
      name: "Data Analyst v2",
      case: "CASE-103",
      mode: "Standard",
      status: "Submitted",
      date: "2026-10-07",
      decision: "Accept",
      reason: "Demonstrated SQL experience meets the published requirements.",
    },
  ],
  users: [
    {
      id: "USR-001",
      name: "research.demo",
      role: "Researcher",
      status: "Active",
      date: "2026-10-08",
    },
    {
      id: "USR-002",
      name: "hr.demo",
      role: "HR",
      status: "Active",
      date: "2026-10-07",
    },
    {
      id: "USR-003",
      name: "candidate.demo",
      role: "Candidate",
      status: "Disabled",
      date: "2026-10-06",
    },
    {
      id: "USR-004",
      name: "admin.demo",
      role: "Admin",
      status: "Active",
      date: "2026-10-08",
    },
  ],
  failures: [
    {
      id: "TASK-001",
      name: "Extraction",
      resource: "CASE-101",
      code: "PDF_TEXT_UNAVAILABLE",
      retryable: true,
      cleanup: "Pending",
      status: "Failed",
    },
    {
      id: "TASK-002",
      name: "Inference",
      resource: "CASE-102",
      code: "MODEL_TIMEOUT",
      retryable: true,
      cleanup: "Not required",
      status: "Failed",
    },
    {
      id: "TASK-003",
      name: "Cleanup",
      resource: "CASE-103",
      code: "FILE_LOCKED",
      retryable: true,
      cleanup: "Pending",
      status: "Failed",
    },
    {
      id: "TASK-004",
      name: "Validation",
      resource: "CASE-104",
      code: "SCHEMA_MISMATCH",
      retryable: false,
      cleanup: "Completed",
      status: "Failed",
    },
  ],
  audits: [
    {
      id: "AUD-001",
      name: "2026-10-08 14:32",
      actor: "USR-001",
      action: "EXPERIMENT_CREATED",
      resource: "EXP-001",
      from: "None",
      to: "Draft",
      status: "Success",
      request: "REQ-a81f",
    },
    {
      id: "AUD-002",
      name: "2026-10-08 14:30",
      actor: "USR-004",
      action: "MODEL_ACTIVATED",
      resource: "N-2026.01",
      from: "Approved",
      to: "Active",
      status: "Success",
      request: "REQ-b10d",
    },
    {
      id: "AUD-003",
      name: "2026-10-08 14:27",
      actor: "USR-002",
      action: "REVIEW_SUBMITTED",
      resource: "REV-003",
      from: "Pending",
      to: "Submitted",
      status: "Success",
      request: "REQ-c29e",
    },
  ],
};
